### ISSUE TITLE
Create pm project directly from git

### ISSUE THREAD

**Issue by jonasdroste** [Angelmmiguel/pm#11]
Hello,
a feature request / idea!
Create pm projects directly from git like:
`pm add git@github.com:Angelmmiguel/pm.git`
and / or
`pm add git@github.com:Angelmmiguel/pm.git [some local folder]`

**Comment by Angelmmiguel** [comment]
Hello @jonasdroste,

That's for the suggestion, It's a good idea! However, `pm` is not directly related with `git`. I'd rather avoid creating folders or cloning projects from `pm`.
