### ISSUE TITLE
Install Failed.MacOS Sierra 10.12.6

### ISSUE THREAD

**Issue by seanxiaoxiang** [Angelmmiguel/pm#12]
<img width="440" alt="96fa4b1f8a45520dfeebb4295877eca6" src="https://user-images.githubusercontent.com/4323376/34597634-e41dc2ec-f222-11e7-8b23-12bed989ad4c.png">
It seem installed successfully.But when I restart my terminal it tell "pm command not fond"
<img width="264" alt="8d253a6fef5dd4500b33b52ae885b6c3" src="https://user-images.githubusercontent.com/4323376/34597639-e7abaf00-f222-11e7-8585-c564aaa62cf9.png">

**Comment by Angelmmiguel** [comment]
Hello @seanxiaoxiang,

It seems the project is correctly installed, but the aliases weren't added to the `.bash_profile`. Could you check the content of `~/.bash_profile`? Is the following code present there?

```
# PM functions
source ~/.pm/pm.zsh
alias pma="pm add"
alias pmg="pm go"
alias pmrm="pm remove"
alias pml="pm list"
# end PM
```

Just to notify you, the `bash` version was an experiment and It's not properly tested. I'm sorry but I didn't continue with the deployment and I'm planning to remove it.

**Comment by seanxiaoxiang** [comment]
It works after add the code you presented.Thanks!By the way ,I just wonder why you plan to remove the bash version?Plenty of programmers work on Mac and the tool you make did help us.

**Comment by seanxiaoxiang** [comment]
It work!!Thanks.

**Comment by Angelmmiguel** [comment]
Glad to hear that!
