### ISSUE TITLE
 I tell me install succeed.But still Command not fond:PM

### ISSUE THREAD

**Issue by seanxiaoxiang** [Angelmmiguel/pm#14]
<img width="360" alt="ea77762a2d7d4a50253dd59adb54559a" src="https://user-images.githubusercontent.com/4323376/35204676-be819928-ff6a-11e7-8f03-19ab91f99acc.png">
I am using zsh.
I told me I had installed.But when I restart my console It still tell me command not found.

<img width="212" alt="dc56da236c7ab664c2d1432eee482caa" src="https://user-images.githubusercontent.com/4323376/35204719-fa6c44e2-ff6a-11e7-8d85-10212b8d9f31.png">

And the path of zsh plugins did can not  find PM .Would you help me?
<img width="215" alt="a158363e-03dc-4bd7-82a9-0029828a3898" src="https://user-images.githubusercontent.com/4323376/35204767-3b21a8ce-ff6b-11e7-824d-d5eb2e08c4a5.png">

**Comment by Angelmmiguel** [comment]
I believe this issue is duplicated #12
