### ISSUE TITLE
PM Events

### ISSUE THREAD

**Issue by rakanalh** [Angelmmiguel/pm#2]
Hello,

I've been looking at this project and thinking that it would be nice to have events implemented into PM so that you can trigger some commands to launch certain apps such as vim on the current directory or activate a python virtualenv.

What do you think?

**Comment by rakanalh** [comment]
Just realised this is already possible with after-all. Thanks

**Comment by Angelmmiguel** [comment]
Hello,

In addition, `after` config is available per project too. Check [Projects](https://github.com/Angelmmiguel/pm#projects) section in the readme :)

**Comment by rakanalh** [comment]
Yup... missed reading those i guess.

Thanks alot :+1:
