### ISSUE TITLE
How to uninstall or remove clearly?

### ISSUE THREAD

**Issue by fangqi179** [Angelmmiguel/pm#22]
mac os catalina install failed. How can I uninstall or remove clearly?

**Comment by Angelmmiguel** [comment]
Hello @fangqi179,

Sorry to hear this tool doesn't work on macOs Catalina. To fully remove it, you only need to delete the `~/.pm` folder and remove the following lines from your `~/.zshrc` file:

```
# PM functions
source ~/.pm/pm.zsh
alias pma="pm add"
alias pmg="pm go"
alias pmrm="pm remove"
alias pml="pm list"
# end PM
```

That's all.

Thanks for trying it!

**Comment by Angelmmiguel** [comment]
@fangqi179 I'm going to close this issue. Please, feel free to reopen it in case you have any other question. Thanks!
