### ISSUE TITLE
Asking for remove file ~/.pm/version on each run

### ISSUE THREAD

**Issue by brpaz** [Angelmmiguel/pm#5]
hello.
Every time I run pm command, I get the following message printed in the terminal:

`rm: remove regular file '/home/bruno/.pm/version'? `

After that the command runs as usual.

**Comment by Angelmmiguel** [comment]
Hello @brpaz,

Thank you for creating the issue. What shell are you using? bash or zsh?

**Comment by brpaz** [comment]
zsh, on Linux Mint 18.3

**Comment by NeodarZ** [comment]
Hello, 

yes I reply after 1 year...

But I have this problem and for me the problem is that is use this alias in my zshrc : `alias rm="rm -i"`.

So just remove this alias and this problem disappear.

Now I have understand the stupidity of an alias who completely replace the original command...

**Comment by Angelmmiguel** [comment]
Np @NeodarZ, this kind of things usually happen. 

Sorry about the long time @brpaz, but to be honest, I'm not maintaining this project very actively. Could you fix the issue? Is it related with the @NeodarZ one?

Thanks!
